import { useEffect, useState, type Dispatch, type SetStateAction } from 'react';
import { createRoot } from 'react-dom/client';
import { api } from './api';
import type { Alert, AppInventory, Overview, Role, UserProfile } from './types';
import './styles.css';
import './overrides.css';

type View='overview'|'alerts'|'detail'|'user'|'apps';
type AlertQuery={page:number;search:string;severity:string;status:string};
const severityRank={critical:4,high:3,medium:2,low:1};
function Badge({children,kind}:{children:React.ReactNode;kind:string}){return <span className={`badge ${kind}`}>{children}</span>}
function ErrorBox({message}:{message:string}){return <div className="error" role="alert">Couldn’t load this data: {message}. <button onClick={()=>location.reload()}>Try again</button></div>}
function App(){const [role,setRole]=useState<Role>('viewer');const [view,setView]=useState<View>('overview');const [overview,setOverview]=useState<Overview>();const [alertRows,setAlertRows]=useState<Alert[]>([]);const [selected,setSelected]=useState<Alert>();const [profile,setProfile]=useState<UserProfile>();const [apps,setApps]=useState<AppInventory[]>([]);const [error,setError]=useState('');const [query,setQuery]=useState({page:1,search:'',severity:'',status:''});const [total,setTotal]=useState(0);const [exportMessage,setExportMessage]=useState('');
 const loadOverview=()=>api.overview().then(setOverview).catch(e=>setError(e.message));
 const loadAlerts=()=>api.alerts(query).then(r=>{setAlertRows(r.items);setTotal(r.total)}).catch(e=>setError(e.message));
 useEffect(()=>{if(view==='overview')loadOverview(); if(view==='alerts')loadAlerts(); if(view==='apps')api.apps().then(setApps).catch(e=>setError(e.message));},[view,query.page,query.search,query.severity,query.status]);
 const openAlert=(a:Alert)=>{setSelected(a);setView('detail')}; const openUser=(id:string)=>api.user(id).then(x=>{setProfile(x);setView('user')}).catch(e=>setError(e.message));
 const nav=(to:View)=>{setError('');setView(to)};
 return <main><a className="skip" href="#content">Skip to content</a><header><div><span className="logo">◐</span><strong>ShadowGuard AI</strong><span className="sub">Human-reviewed Shadow IT triage</span></div><label>Role <select value={role} onChange={e=>setRole(e.target.value as Role)} aria-label="Demo role"><option value="viewer">Viewer</option><option value="analyst">Analyst</option></select></label></header><div className="demo">Demo data — this dashboard is using clearly marked mock records. Configure <code>VITE_API_URL</code> and set <code>VITE_USE_MOCKS=false</code> to connect your API.</div><div className="shell"><nav aria-label="Primary navigation"><button className={view==='overview'?'active':''} onClick={()=>nav('overview')}>Overview</button><button className={view==='alerts'||view==='detail'?'active':''} onClick={()=>nav('alerts')}>Alerts</button><button className={view==='apps'?'active':''} onClick={()=>nav('apps')}>Discovery map</button></nav><section id="content" className="content">{error&&<ErrorBox message={error}/>} {view==='overview'&&<OverviewPage data={overview} openAlert={openAlert} openUser={openUser}/>} {view==='alerts'&&<AlertsPage rows={alertRows} total={total} query={query} setQuery={setQuery} openAlert={openAlert}/>} {view==='detail'&&selected&&<DetailPage alert={selected} role={role} back={()=>nav('alerts')} openUser={openUser}/>} {view==='user'&&profile&&<UserPage profile={profile} openAlert={openAlert} back={()=>nav('alerts')}/>} {view==='apps'&&<AppsPage apps={apps} role={role} requestExport={async()=>{try{const r=await api.exportRequest();setExportMessage(`Redacted export request ${r.requestId} was sent to the server.`)}catch(e){setError((e as Error).message)}}} message={exportMessage}/>}</section></div></main>}
function OverviewPage({data,openAlert,openUser}:{data?:Overview;openAlert:(a:Alert)=>void;openUser:(id:string)=>void}){if(!data)return <p className="loading">Loading overview…</p>;return <><div className="title"><div><p className="eyebrow">Security operations</p><h1>Review what needs attention</h1><p>Signals support a human decision; they do not prove intent.</p></div></div><div className="cards">{Object.entries(data.severityCounts).sort(([a],[b])=>severityRank[b as keyof typeof severityRank]-severityRank[a as keyof typeof severityRank]).map(([k,v])=><article className="metric" key={k}><span className={`dot ${k}`}/><b>{v}</b><span>{k} alerts</span></article>)}<article className="metric"><b>{data.newApps}</b><span>new apps this week</span></article><article className="metric"><b>{data.reviewedThisWeek}</b><span>reviewed this week</span></article></div><section className="panel"><h2>Top risk for review</h2><div className="table">{data.topRisk.map(a=><button className="row" onClick={()=>openAlert(a)} key={a.id}><span><b>{a.userName}</b><small>{a.department} · {a.app}</small></span><Badge kind={a.severity}>{a.severity}</Badge><b>{a.score}</b><span aria-hidden>›</span></button>)}</div><button className="link" onClick={()=>openUser(data.topRisk[0].userId)}>Open user risk profile</button></section></>}
function AlertsPage({rows,total,query,setQuery,openAlert}:{rows:Alert[];total:number;query:AlertQuery;setQuery:Dispatch<SetStateAction<AlertQuery>>;openAlert:(a:Alert)=>void}){const pages=Math.max(1,Math.ceil(total/5));return <><div className="title"><div><p className="eyebrow">Alert queue</p><h1>Evidence-first review</h1></div></div><div className="filters"><input aria-label="Search alerts" placeholder="Search person or app" value={query.search} onChange={e=>setQuery({...query,search:e.target.value,page:1})}/><select aria-label="Severity" value={query.severity} onChange={e=>setQuery({...query,severity:e.target.value,page:1})}><option value="">All severities</option>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Status" value={query.status} onChange={e=>setQuery({...query,status:e.target.value,page:1})}><option value="">All statuses</option><option value="new">New</option><option value="under_review">Under review</option><option value="resolved">Resolved</option></select></div><section className="panel"><div className="table header"><span>Person / application</span><span>Severity</span><span>Score</span><span/></div>{rows.length?rows.map(a=><button className="row" key={a.id} onClick={()=>openAlert(a)}><span><b>{a.userName}</b><small>{a.app} · {a.category} · {a.id}</small></span><Badge kind={a.severity}>{a.severity}</Badge><b>{a.score}</b><span>›</span></button>):<p className="empty">No alerts match these filters.</p>}<div className="pagination"><span>{total} alert{total===1?'':'s'}</span><button disabled={query.page===1} onClick={()=>setQuery({...query,page:query.page-1})}>Previous</button><span>Page {query.page} of {pages}</span><button disabled={query.page===pages} onClick={()=>setQuery({...query,page:query.page+1})}>Next</button></div></section></>}
function DetailPage({alert,role,back,openUser}:{alert:Alert;role:Role;back:()=>void;openUser:(id:string)=>void}){return <><button className="back" onClick={back}>← All alerts</button><div className="title"><div><p className="eyebrow">{alert.id} · {alert.category}</p><h1>{alert.app} activity for {alert.userName}</h1><p><Badge kind={alert.severity}>{alert.severity}</Badge> Risk score <b>{alert.score}/100</b> · Recommendation tier <b>{alert.tier}</b></p></div><button className="link" onClick={()=>openUser(alert.userId)}>Open user profile</button></div><div className="detailgrid"><section className="panel"><h2>What we observed</h2><p className="hint">These contributors are evidence and context, not a determination of intent.</p><ol className="timeline">{alert.evidence.map((e,i)=><li key={i}><span className={`point ${e.strength}`}/><div><b>{e.label}</b><small>{e.observedAt} · {e.strength==='observed'?'Observed signal':'Review context'}</small><p>{e.detail}</p></div></li>)}</ol></section><aside className="panel action"><p className="eyebrow">Recommended human action</p><h2>{alert.recommendation}</h2><p>Reviewers should validate the evidence and policy context before changing access or notifying anyone.</p>{role==='analyst'?<button className="primary">Mark as reviewed</button>:<><button className="primary" disabled>Mark as reviewed</button><small>Viewer role: review controls are unavailable.</small></>}</aside></div></>}
function UserPage({profile,openAlert,back}:{profile:UserProfile;openAlert:(a:Alert)=>void;back:()=>void}){const max=Math.max(...profile.trend);return <><button className="back" onClick={back}>← Alerts</button><div className="title"><div><p className="eyebrow">User risk profile</p><h1>{profile.name}</h1><p>{profile.department} · Baseline <Badge kind={profile.baseline}>{profile.baseline}</Badge></p></div></div><div className="detailgrid"><section className="panel"><h2>Risk trend</h2><div className="trend" aria-label="Risk trend over six review periods">{profile.trend.map((x,i)=><div key={i}><span style={{height:`${Math.max(10,x/max*100)}%`}} title={`Period ${i+1}: ${x}`}/><small>{x}</small></div>)}</div><p className="hint">Trend shows scores across six review periods. It is not a prediction.</p></section><section className="panel"><h2>Application inventory</h2>{profile.inventory.map(x=><div className="inventory" key={x}><span>{x}</span><Badge kind="review">Observed</Badge></div>)}</section></div><section className="panel"><h2>Alert history</h2>{profile.alerts.map(a=><button className="row" key={a.id} onClick={()=>openAlert(a)}><span><b>{a.app}</b><small>{new Date(a.createdAt).toLocaleString()}</small></span><Badge kind={a.severity}>{a.severity}</Badge><b>{a.score}</b><span>›</span></button>)}</section></>}
function AppsPage({apps,role,requestExport,message}:{apps:AppInventory[];role:Role;requestExport:()=>void;message:string}){return <><div className="title"><div><p className="eyebrow">Application discovery</p><h1>Inventory for review</h1><p>Approval status reflects the tenant’s inventory, not a safety judgment.</p></div><div>{role==='analyst'?<button className="primary" onClick={requestExport}>Request redacted export</button>:<button className="primary" disabled>Request redacted export</button>}<small className="block">{role==='viewer'?'Viewer role: export requests are unavailable.':'Server generates and redacts exports; this browser does not cache them.'}</small></div></div>{message&&<div className="success" role="status">{message}</div>}<section className="panel apps"><div className="appheader"><span>Application</span><span>Category</span><span>Approval</span><span>Active users</span><span>Review</span></div>{apps.length?apps.map(a=><div className="approw" key={a.id}><b>{a.name}</b><span>{a.category}</span><Badge kind={a.approval}>{a.approval}</Badge><span>{a.activeUsers}</span><Badge kind={a.review}>{a.review}</Badge></div>):<p className="loading">Loading inventory…</p>}</section></>}
createRoot(document.getElementById('root')!).render(<App/>);
