import type { Alert, AppInventory, Overview, UserProfile } from './types';

export const alerts: Alert[] = [
 { id:'AL-1042', userId:'u-1', userName:'Maya Chen', department:'Marketing', severity:'high', score:78, app:'Perplexity AI', category:'Shadow AI', status:'new', createdAt:'2026-08-10T09:14:00Z', tier:'R3', recommendation:'Flag for IT review. Confirm whether a sanctioned research tool meets the team’s need.', evidence:[{label:'New application observed',detail:'Perplexity AI is not in the approved application inventory.',observedAt:'09:14',strength:'observed'},{label:'Usage outside baseline',detail:'Activity occurred 3 hours after Maya’s established work window.',observedAt:'09:14',strength:'observed'},{label:'Peer context',detail:'12% of Marketing has used this app; below evaluation threshold.',observedAt:'09:15',strength:'context'}] },
 { id:'AL-1041', userId:'u-2', userName:'Jordan Rivers', department:'Sales', severity:'critical', score:93, app:'Personal Google Drive', category:'Personal cloud', status:'under_review', createdAt:'2026-08-10T02:18:00Z', tier:'R6', recommendation:'Escalate to security for human review. Do not take automated enforcement action.', evidence:[{label:'Volume anomaly',detail:'Upload volume is 4.8× the 30-day user baseline.',observedAt:'02:18',strength:'observed'},{label:'Time anomaly',detail:'Activity occurred outside the user’s normal work hours.',observedAt:'02:18',strength:'observed'},{label:'Known personal-cloud category',detail:'Destination is categorized as personal cloud storage.',observedAt:'02:19',strength:'context'}] },
 { id:'AL-1039', userId:'u-3', userName:'Alex Morgan', department:'Sales', severity:'medium', score:66, app:'Notion AI', category:'Shadow AI', status:'new', createdAt:'2026-08-09T15:33:00Z', tier:'R4', recommendation:'Recommend sanctioned-alternative evaluation because use is widespread in this peer group.', evidence:[{label:'Peer prevalence',detail:'43% of Sales has active use of this application.',observedAt:'15:34',strength:'observed'},{label:'Unapproved app',detail:'Notion AI is not yet approved for this tenant.',observedAt:'15:33',strength:'observed'}] },
 { id:'AL-1037', userId:'u-1', userName:'Maya Chen', department:'Marketing', severity:'low', score:42, app:'Canva', category:'Unauthorized SaaS', status:'resolved', createdAt:'2026-08-08T11:20:00Z', tier:'R2', recommendation:'Notify employee and offer a self-audit prompt.', evidence:[{label:'First observation',detail:'First observed use in the current review window.',observedAt:'11:20',strength:'observed'}] }
];
export const applications: AppInventory[] = [
 {id:'a1',name:'Perplexity AI',category:'Shadow AI',approval:'unapproved',activeUsers:7,review:'needed'}, {id:'a2',name:'Notion AI',category:'Shadow AI',approval:'review',activeUsers:18,review:'in progress'}, {id:'a3',name:'Google Workspace',category:'Collaboration',approval:'sanctioned',activeUsers:148,review:'complete'}, {id:'a4',name:'Personal Google Drive',category:'Personal cloud',approval:'unapproved',activeUsers:3,review:'needed'}
];
export const overview: Overview = { severityCounts:{low:6,medium:9,high:4,critical:1}, newApps:3, reviewedThisWeek:14, topRisk:alerts.slice(0,3) };
export const profiles: Record<string, UserProfile> = { 'u-1': {id:'u-1',name:'Maya Chen',department:'Marketing',baseline:'established',trend:[32,38,41,55,61,78],inventory:['Canva','Perplexity AI','Google Workspace'],alerts:alerts.filter(a=>a.userId==='u-1')}, 'u-2':{id:'u-2',name:'Jordan Rivers',department:'Sales',baseline:'established',trend:[25,22,28,31,64,93],inventory:['Google Workspace','Personal Google Drive'],alerts:alerts.filter(a=>a.userId==='u-2')}, 'u-3':{id:'u-3',name:'Alex Morgan',department:'Sales',baseline:'learning',trend:[20,24,33,45,55,66],inventory:['Notion AI','Google Workspace'],alerts:alerts.filter(a=>a.userId==='u-3')} };
